plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.mza.mzor'
    compileSdk 34

    defaultConfig {
        applicationId "ir.mza.mzor"
        minSdk 21
        targetSdk 34
        versionCode 11
        versionName "1.4.4"

        def marketApplicationId = "ir.mservices.market"
        def marketBindAddress = "ir.mservices.market.InAppBillingService.BIND"
        manifestPlaceholders += [
                marketApplicationId: marketApplicationId,
                marketBindAddress  : marketBindAddress,
                marketPermission   : "${marketApplicationId}.BILLING"
        ]
    }

    signingConfigs {
        release {
            def ksPath = System.getenv("MZA_KEYSTORE_PATH")
            if (ksPath != null) {
                storeFile file(ksPath)
                storePassword System.getenv("MZA_KEYSTORE_PASSWORD")
                keyAlias System.getenv("MZA_KEY_ALIAS")
                keyPassword System.getenv("MZA_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv("MZA_KEYSTORE_PATH") != null) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'com.github.myketstore:myket-billing-client:1.19'
}
